[package]
name = "cjrh-moreutils-combine"
version = "0.1.4"
edition.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[[bin]]
name = "combine"
path = "src/main.rs"

[dependencies]
cjrh-moreutils-common.workspace = true
libc.workspace = true

[dev-dependencies]
tempfile.workspace = true
