[package]
name = "cjrh-moreutils-parallel"
version = "0.1.3"
edition.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[[bin]]
name = "parallel"
path = "src/main.rs"

[dependencies]
cjrh-moreutils-common.workspace = true

[dev-dependencies]
tempfile.workspace = true
